version: '3.8'


services:
  # Application Service
  app:
    container_name: blog
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    depends_on:
      - localhost
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=livedata
      - DB_USERNAME=postgres
      - DB_PASSWORD="Nepal@323"  


  # Database Service
  localhost:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      # - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped  
    environment:
      POSTGRES_DB: livedata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Nepal@323"


  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - localhost


  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - localhost
    environment:
      PGADMIN_DEFAULT_EMAIL: bikram@gmail.com
      PGADMIN_DEFAULT_PASSWORD: bik123
