name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, sqlite3, bcmath, sodium

      - name: Install Composer dependencies
        run: cd src && composer install --prefer-dist --no-interaction --no-scripts --no-progress

      - name: Run database migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: storage/logs/*.log
